### ISSUE TITLE
Code Review on 7/16 Issues

### ISSUE THREAD

**Issue by bothemrun** [bothemrun/Chat-Room-v1#31]
## Code Review on 7/16
- finish registration requirement

## TODO: Code Review Issues
- [x] server.js:240, fix `==` to `===`
- [x] may use HTTP PUT for login
- [x] `/register` path renaming by RESTful API conventions [RESTful API Best Practices](https://www.vinaysahni.com/best-practices-for-a-pragmatic-restful-api)
- [x] catch db error
- [x] for validating username & password, use better SQL
- [x] chat.html:8 no "" for script src
