### ISSUE TITLE
MVC Refactor + Singleton + Private Messaging

### ISSUE THREAD

**Issue by bothemrun** [bothemrun/Chat-Room-v1#34]
# Private Messaging

## (A) room selection frontend & html page
- 1. after login, redirect to the room selection page
- 2. after the user selects a room, redirect to the room's URL
- 3. in previous version, the chat page has the URL ```host:port/```, but now each room's chat page has its own URL ```host:port/chat/:room_id```

## (B) socket.io on connection, join the user's all rooms
- 1. when the socket.io server gets a connection event:
- 2. get all rooms of the user from db, 
- 3. then join the user to all of the rooms.
- 4. so we don't have worry about how to get room_id from client
- 5. so if room_a sends a message to client's room_b page, then the room_b's frontend socket.io event listener has to rule out messages other than room_b.

## (C) the rest is just like when there is the only public chat room
- 1. just wrap the public chat room ```host:port/chat``` with a URL ```host:port/chat/:room_id```

## (D) Task Breakdown
- [x] read the codebase and get familiar with the codes again. (8/25 12:10 due)
- [x] remove old socket.io private messaging implementation. (12:30 due)
- [x] fix some chores.  use ```textarea``` to replace ```input``` in html. (13:00 due)
- [x] each chat room has its own URL. (13:40 due)
- [x] room selection html. (8/25 15:10 due)
- [x] room selection frontend. (8/26 16:53 due)
- [x] after login, redirect to room selection page. (8/26 16:53 due)
- [x] add room creation to room selection html. (8/27 10:00 due)
- [x] add room creation frontend to room selection frontend by RESTful API ```POST /rooms/:room_id```. (8/27 10:30 due)
- [x] on each room page, the go to room selection page button. (8/27 11:00 due)
- [x] fix: when POST /rooms, duplicate usernames. (8/27 11:30 due)
- [x] doc: understand session store (8/27 16:30 due)
- figure out the way for the server to get session data (except for req.session)
- in branch doc/success-session-store-try
- see merge pull #68 
- [x] when socket.io server on connection event, join the user to all of the user's rooms. (8/28 10:10 due)
- (this is a better system design for notification).
- see merge pull #68 
- [x] show room_id on chat room page. (8/28 10:10 due)
- [x] utility function for redirect & reloads. (8/28 13:54 due)
- Browser can't use ```require()``` , so must use ES6 ```import``` for the utility.
- see merge pull #69 
- [x] summarize private messaging. (8/28 15:30 due)
- [ ] branch ```doc/success-session-store-try``` , why module dependency problem originally?

#### socket.io Reference
- socket.io ```io.to("room1").emit(...)```
- [emit cheatsheet](https://socket.io/docs/v3/emit-cheatsheet/)
- [socket.io rooms](https://socket.io/docs/v3/rooms/)

# Summarize Private Messaging
- achieved end-to-end feature development from scratch:
- from UI, Database Schema, Design Doc, API Design, To Backend, Frontend, HTML, CSS.

## Task Breakdown & Best Practices
- when designing a new (complex) feature from scrach (UI, design doc, backend, frontend), task breakdown is crucial.
- due to its complexity, best practices of merge pulls, multiple local commit in a pull request, trial branches are crucial.

## Architecture & Design Patterns: MVC, Singleton, Module/Class Encapsulation
- as complexity grows, architecture and design patterns are crucial.
- browser frontend import see merge pull #69 
#### try to avoid module mutual dependency
- Notes & Guides see merge pull #53 

## Session Store
- used session instead of json web token for authentication.
- session stores data in server side, unlike token.
- I stored client data like usernames in session, so I have to access the express session store with sessionID got from socket.io socket on connection event.
- see merge pull #68 

## socket.io
- can print socket to see its properties not explained in socket.io documentation website
- I parsed socket ```socket.request.headers.cookie``` to get sessionID
- see merge pull #68 

#### to register event listener ```on(event, handler)``` , register them in the ```connection``` event handler.
- why? since client doesn't have socket.io server instance, and server side's ```connection``` event has the client's socket instance.

## System Design & Design Doc
- It's crucial and saves me from "development derailing".  For example:
- ```where and how to use socket.io join(room_id) ?? server or client side??```

#### my original design was:
- each chat room has the URI ```/``` without any information
- the room_id was got from client side frontend global variable.
- and get username and room_id from in client side,
- and then emit a socket.io event to tell the server to use socket.io ```join()```
- so I was stuck at the point: ```how does server get to know client's socket.io socket ???```

#### new design is:
- each chat room has the URI ```/rooms/:room_id``` with room_id information.
- then both the server and the client can know room_id, by ```req.params``` and ```window.location.pathname``` respectively
- for the server on socket.io connection event,
- how do we get the socket.io socket's username?  by parsing socket to get sessionID and then use session store API ```store.get(sessionID, callback(error, session){ ... })``` to get session data.
- then we retrieve all the username's rooms from database by the username in session data.
- then we use socket.io join(room_id) 
- for client side, frontend filters new messages whose room_id equals its room_id
- this is a better design --> notification

# MVC refactor
#### mvc express example
- https://progressivecoder.com/how-to-create-a-nodejs-express-mvc-application/
- https://github.com/dashsaurabh/node-express-mvc-demo/tree/master

#### mvc class
- ```docs/mvc-demo.py```

### Login_Page class
- just sendFile login.html
### Chat_Room class
- just sendFile chat.html

#### application / root / router-level middleware for decoupling express main and routing.
- https://expressjs.com/en/guide/using-middleware.html#middleware.router
- https://expressjs.com/en/guide/using-middleware.html#middleware.application
- https://expressjs.com/en/guide/using-middleware.html

# Singleton
- Notes & Guides see merge pull #53 
- [ ] ES6 Modules: [Support for cyclic dependencies between modules](https://2ality.com/2014/09/es6-modules-final.html) ??? not yet read.
